// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyContacts.Server.Data;

#nullable disable

namespace MyContacts.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyContacts.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Prywatny"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Służbowy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Inny"
                        });
                });

            modelBuilder.Entity("MyContacts.Shared.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateOfBirth = new DateTime(1999, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cLeclerc@gmail.com",
                            FistName = "Charles",
                            LastName = "Leclerc",
                            Password = "abc123",
                            PhoneNumber = 506432523,
                            SubCategory = ""
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateOfBirth = new DateTime(1981, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lHam44@gmail.com",
                            FistName = "Lewis",
                            LastName = "Hamilton",
                            Password = "abc123",
                            PhoneNumber = 677312444,
                            SubCategory = ""
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateOfBirth = new DateTime(1997, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fAlonso@gmail.com",
                            FistName = "Fernando",
                            LastName = "Alonso",
                            Password = "235634",
                            PhoneNumber = 111222145,
                            SubCategory = ""
                        });
                });

            modelBuilder.Entity("MyContacts.Shared.Contact", b =>
                {
                    b.HasOne("MyContacts.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
